travis:
  secure:
    BINSTAR_TOKEN: XMrk5ZWVNncilMb3Djh1dToKSJT1HZ0a9Sdal8raqJWZIVGw4av2OVKsuTxQteSqVj49x9UxndxMy1L2KeNCT/SAkzq/0FGEncmV6to/pgTn5ORsMGLehZ6xvtUkgpHmBWtD4JSkwrlQdQ7ArdFWTA3to8x3ldbO/eY1UnjYwVlv/w2OwK5DzYxK02Q72lfSFVzcUAVm+cNIXTj/riZZOgncHvpEBR4n1heioja0OzfapXJgdTE5K/4NSqc9fwNYIQWnfawZ3AguGgT88rbmoXE/rqwuJvgKTGx+puyUq5LUKg+O7uhjLrP01JiAYW0sNkTsjmCrdZKXCleNvrntHrSfM4y4P8R9r32gJRVBhueQ1uf/DvChfwpVnCdVxgdIsVorrtcvalJhDRs3kyb7vfFSGmvRQ7U4aJ774VKjaantw4QKsy2jI5t461Pt/q5LuGGAsoPxJzzXlCHP82rwRjrcDFOLkJRKnnKBAAsHKLADSXNza8F9rE2uc7+TD0npWDOrbaChHnKUKGwd4GJC1SOFQwd1qf/NWbIzFdpwlMJM6tN+cVA3aZ6NNUJjMTgIdtLdxa/UD8iE0drOeeYeZsT8x5/CqyOe3LwJj3Oo1E9HVq1QZotUjrYB46MeCYHnIbnF4jYXAabK2GgOg9nJwH4Yu4/wGUe4RcLPplMDDLw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
